#!/bin/bash

set +e

if [[ $EUID -ne 0 ]] 
then
  echo -e "\n Please run script as ROOT $END"
  exit 1
fi

rm /var/lib/apt/lists/lock 
rm /var/cache/apt/archives/lock
rm /var/lib/dpkg/lock

dpkg --configure -a 

apt autoremove -y
apt clean -y

apt "${@:1}"
